# Generated by Django 5.0.13 on 2025-07-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('doc', '文件'), ('img', '圖片'), ('vid', '影片'), ('aud', '音訊'), ('oth', '其他')], max_length=10, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo')),
            ],
            options={
                'db_table': 'my_app_UploadedFile',
            },
        ),
    ]
