# Generated by Django 5.0.13 on 2025-07-13 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_app_ImageAnalysis',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('DataID', models.CharField(db_column='DataID', max_length=32, primary_key=True, serialize=False)),
                ('CreateID', models.CharField(db_column='CreateID', max_length=30)),
                ('CreateDate', models.DateTimeField(db_column='CreateDate', default=django.utils.timezone.now)),
                ('UpdateID', models.CharField(db_column='UpdateID', max_length=30)),
                ('UpdateDate', models.DateTimeField(db_column='UpdateDate', default=django.utils.timezone.now)),
                ('DataFlag', models.BinaryField(db_column='DataFlag', max_length='max')),
                ('UserID', models.CharField(db_column='UserID', max_length=20)),
                ('UserName', models.CharField(db_column='UserName', max_length=100, unique=True)),
                ('Password', models.TextField(db_column='Password')),
            ],
            options={
                'db_table': 'my_app_userinfo',
            },
        ),
    ]
